#define PRIVATE 0
#define PROTECTED 1
#define PUBLIC 2

#define FALSE 0
#define TRUE 1

#define HEADLESS_CLIENT 0
#define HEADED_CLIENT 512
#define HEADED_CLIENT_HOST 768
#define DEDICATED_SERVER 384

#define IDC_HUD 7736
#define IDC_MINIMAP 7734

// GUI
#define CT_MAP_MAIN 101
#define ST_PICTURE 48
#define CT_STATIC 0
#define CT_BUTTON 1
